name: gyzyleller
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #==================== FIREBASE ====================#
  firebase_core: ^3.1.1
  firebase_core_platform_interface: ^6.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^19.4.0

  #==================== STATE MANAGEMENT ====================#
  get: ^4.7.2

  #==================== NETWORK ====================#
  http:
  web_socket_channel: ^3.0.3

  #==================== UI & UX ====================#
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  dotted_border: ^2.1.0
  hugeicons: ^0.0.11
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  upgrader: ^10.3.0

  #==================== LOCAL STORAGE ====================#
  get_storage: ^2.1.1

  #==================== UTILITIES ====================#
  kartal: ^3.5.0
  intl: ^0.20.2
  url_launcher: ^6.2.1

  #==================== MEDIA ====================#
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.5.0
  flutter_svg: ^2.0.10+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: assets/fonts/Helvetica.ttf
          weight: 400