// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android — values from google-services.json (project: gyzyleller-d1cb3)
 static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyCnviagkclA2x1MaG5tBv1ODq4xlV2f0BI',
  appId: '1:406458755749:android:a168a4597d81e3ab683b4c',
  messagingSenderId: '406458755749',
  projectId: 'ayterek-5c3e8',
  storageBucket: 'ayterek-5c3e8.firebasestorage.app',
);

  // iOS — update appId/apiKey from GoogleService-Info.plist if needed
static const FirebaseOptions ios = FirebaseOptions(
  apiKey: 'AIzaSyDvdYXxhYTUH4sjlff9MYrRMFyRXwjUCdk',
  appId: '1:406458755749:ios:d106f1c09c36358e683b4c',
  messagingSenderId: '406458755749',
  projectId: 'ayterek-5c3e8',
  storageBucket: 'ayterek-5c3e8.firebasestorage.app',
  iosBundleId: 'com.ayterek.hyzmatlar',
);
}