// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android — values from google-services.json (project: gyzyleller-d1cb3)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQiCodPj_pgcNb8NBXR4pTT65p2KdD_OE',
    appId: '1:261474756113:android:e2878f232a7445148c73b0',
    messagingSenderId: '261474756113',
    projectId: 'gyzyleller-d1cb3',
    storageBucket: 'gyzyleller-d1cb3.firebasestorage.app',
  );

  // iOS — update appId/apiKey from GoogleService-Info.plist if needed
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8uZGzY9QQP4lkb04GXIh1kOYvkdW8ws8',
    appId: '1:261474756113:ios:ae9591870dae98cc8c73b0',
    messagingSenderId: '261474756113',
    projectId: 'gyzyleller-d1cb3',
    storageBucket: 'gyzyleller-d1cb3.firebasestorage.app',
    iosBundleId: 'com.ayterek.hyzmatlar',
  );
}